# Generated by Django 5.1.1 on 2024-10-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_delete_anomaly'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkTraffic',
        ),
        migrations.AddField(
            model_name='performancemetrics',
            name='average_throughput',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='performancemetrics',
            name='connection_time',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='performancemetrics',
            name='jitter',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='performancemetrics',
            name='latency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='performancemetrics',
            name='max_throughput',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='performancemetrics',
            name='packet_loss',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='performancemetrics',
            name='throughput',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='download_speed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='ping',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='upload_speed',
            field=models.FloatField(default=0.0),
        ),
    ]
